name: An R workflow to automate H7 latest changes csv 
on: push
#        schedule:
#                - cron: '0 * * * *'

jobs: 
        build:
                name: R github actions
                runs-on: ubuntu-latest
                steps: 
                        - uses: actions/checkout@master
                        - uses: r-lib/actions/setup-r@master
                          with: 
                                  r-version: '3.5.3' # The R version to be installed 
                        - name: Install dependencies        
                          run: |
                             ls
                             chmod +x codes/sysrequirements_h7changes.sh
                             ./codes/sysrequirements_h7changes.sh
                        - name: Run regional changes updates code
                          run: |
                            ls
                            echo 'Starting data prep code'
                            Rscript -e codes/H7_latestchanges.R
                        - name: Commit changes
                          run: |
                            ls
                            echo 'Committing output'
                            git config --local user.email "action@github.com"
                            git config --local user.name "GitHub Action"
                            git add .
                            git diff-index --quiet HEAD || git commit -m "Adding latest H7 changes" -a
                        - name: Push changes
                          uses: ad-m/github-push-action@master
                          with:
                            github_token: ${{ secrets.GITHUB_TOKEN }}
